-- "addons\\homigrad-weapons\\lua\\weapons\\homigrad_base\\init.lua"
-- Scripthooked by ???
--
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_anim.lua")
AddCSLuaFile("sh_bullet.lua")
AddCSLuaFile("sh_replicate.lua")
AddCSLuaFile("sh_holster_deploy.lua")
AddCSLuaFile("sh_reload.lua")
AddCSLuaFile("sh_spray.lua")
AddCSLuaFile("sh_worldmodel.lua")
AddCSLuaFile("sh_attachment.lua")
AddCSLuaFile("sh_fake.lua")
AddCSLuaFile("sh_ammo.lua")
AddCSLuaFile("sh_weaponsinv.lua")
AddCSLuaFile("cl_camera.lua")
AddCSLuaFile("cl_camera_wep.lua")
AddCSLuaFile("cl_optics.lua")
AddCSLuaFile("cl_shells.lua")

include("shared.lua")
include("sh_anim.lua")
include("sh_bullet.lua")
include("sh_replicate.lua")
include("sh_holster_deploy.lua")
include("sh_reload.lua")
include("sh_spray.lua")
include("sh_worldmodel.lua")
include("sh_attachment.lua")
include("sh_fake.lua")
include("sh_ammo.lua")
include("sh_weaponsinv.lua")
include("sv_worldmodel.lua")